// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAv-bEqLqA73RIL6CJOnV4OVTuARbwDGU',
    appId: '1:854157792892:web:617e4374b0be4573b51bf9',
    messagingSenderId: '854157792892',
    projectId: 'quiz-cbdaa',
    authDomain: 'quiz-cbdaa.firebaseapp.com',
    storageBucket: 'quiz-cbdaa.firebasestorage.app',
    measurementId: 'G-2G4MMZ5CKF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIMJQnAjMmJAwXa2cE3n9fnSfuWwSwtf0',
    appId: '1:854157792892:ios:ef87c390f05dac0fb51bf9',
    messagingSenderId: '854157792892',
    projectId: 'quiz-cbdaa',
    storageBucket: 'quiz-cbdaa.firebasestorage.app',
    iosBundleId: 'com.example.quizziz',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIMJQnAjMmJAwXa2cE3n9fnSfuWwSwtf0',
    appId: '1:854157792892:ios:ef87c390f05dac0fb51bf9',
    messagingSenderId: '854157792892',
    projectId: 'quiz-cbdaa',
    storageBucket: 'quiz-cbdaa.firebasestorage.app',
    iosBundleId: 'com.example.quizziz',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LdJpokwNj_xrUhyGRCr-D5WsGkE6bsI',
    appId: '1:854157792892:android:b191e65a2b2e3f30b51bf9',
    messagingSenderId: '854157792892',
    projectId: 'quiz-cbdaa',
    storageBucket: 'quiz-cbdaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAv-bEqLqA73RIL6CJOnV4OVTuARbwDGU',
    appId: '1:854157792892:web:2aecb1e3a6c2d31cb51bf9',
    messagingSenderId: '854157792892',
    projectId: 'quiz-cbdaa',
    authDomain: 'quiz-cbdaa.firebaseapp.com',
    storageBucket: 'quiz-cbdaa.firebasestorage.app',
    measurementId: 'G-FK43CC6MW7',
  );

}